### ISSUE TITLE
GitHub API rate limit

### ISSUE THREAD

**Issue by manuel-scharf-snkeos** [CycloneDX/cyclonedx-gomod#221]
In GitHub I use CycloneDX/gh-gomod-generate-sbom@d4aee0cf5133055dbd98899978246c10c18c440f with version: v1.3.0
And receive the following: Error: API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

How can I get cyclonedx-gomod to do authenticated requests?

It seems like there is no respective parameter compared to [cyclonedx-dotnet](https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/README.md#options)
`-gu|--github-username <GITHUB_USERNAME>
-gt|--github-token <GITHUB_TOKEN>
-gbt|--github-bearer-token <GITHUB_BEARER_TOKEN>`

Additionally, I'm surprised that the rate limit is as well hit with the parameter `licenses=false`, any ideas?

**Comment by nscuro** [comment]
Hi @manuel-scharf-snkeos, cyclonedx-gomod does not interact with the GitHub API directly, so I'm a little at loss as to how it could even contribute to your rate limit being exceeded. cyclonedx-dotnet uses GitHub for license identification, but cyclonedx-gomod does it all locally.

The GitHub Action you use to download cyclonedx-gomod interacts with the GitHub API in order to perform the download.

Have you tried this?

```yaml
 name: Generate SBOM
  uses: CycloneDX/gh-gomod-generate-sbom@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    version: v1.3.0
```
