### ISSUE TITLE
Question: using the gh-gomod-generate-sbom action, fails when execution the "Cheap trick" gocmd.ModWhy call

### ISSUE THREAD

**Issue by jeroendee** [CycloneDX/cyclonedx-gomod#230]
## Problem
Currently I'm trying to integratie the generation of a SBOM for one of our Go repos. The [gh-gomod-generate-sbom](https://github.com/marketplace/actions/cyclonedx-gomod-generate-sbom) action is used. This actually fails with the error:

```json
{"level":"error","error":"failed to download modules: command `/usr/bin/go mod why -m -vendor github.com/CycloneDX/cyclonedx-go` failed: exit status 1","time":"2022-12-16T16:28:08Z"}
```

Looking at [this](https://github.com/CycloneDX/cyclonedx-gomod/blob/0313c5f801f55fcb38d7d18aa5b5f8c68b7667f4/pkg/generate/mod/generator.go#L69) line and the subsequent call to gocmd.ModWhy the error "failed to download modules: ..." doesn't actually indicate a failure of downloading modules, but more generally a failure when running the command (in this case `go mod why -m -vendor github.com/CycloneDX/cyclonedx-go).

On a local dev machine it works. 

## Question
Can somebody explain the above error when running cyclonedx-gomod through a GitHub Action? 

Below the contents of the action:
```
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
       
      - name: Install cyclonedx-gomod
        uses: CycloneDX/gh-gomod-generate-sbom@v1
        with:
          version: v1
      - name: Generate SBOM
        run: cyclonedx-gomod mod -verbose -json -output sbom.json ${{ github.workspace }}
```
